### ISSUE TITLE
Support for Swift Package manager?

### ISSUE THREAD

**Issue by grill2010** [bradhowes/Joystick#11]
Hi, thanks for your nice library. This is just a suggestion as I'm relatively new to Swift I find the Swift Package manager very convenient so I was just wondering if you could add support for that? If this is something you don't want to offer feel free to close this :)

**Comment by bradhowes** [comment]
This would be a very good capability to have. I will look into it.

**Comment by bradhowes** [comment]
Version 3.1.2 should now be usable via SPM. Can you please verify that this is the case for you?
