### ISSUE TITLE
3 Issues I wanted to ask you

### ISSUE THREAD

**Issue by jungwook8580** [bradhowes/Joystick#3]
#1 Can i  touch both joystick simultaneously?
      Since i have no iOS device, i haven't tested on iOS device. Only see that is working on simulator in 
      the Xcode... Do you know it is working if i press both joystick at the same time?

#2 Moving both joystick with pressing exterior area
     I think pulling the base from interior circle is also a great but i want to try moving base pressing 
     external  area from joystick... Can you have any suggestions like adding more code for pressing 
     external area to draw joysticks or revising the current source?

#3 References for your project
     Thank you again for sharing this code on github! Can you share me about the references for  
     creating this wonderful joystick? I am really new to coregraphic framework... so it was really helpful 
     with your comment to understand your code but it would be great if you add references while you 
     are creating your projects! Thank you very much!

**Comment by bradhowes** [comment]
1. Yes. Each joystick is completely independent of any other one.

1. I don't understand what you want. Can you explain what you mean by "pressing" and "exterior area"? Perhaps you want to move the joystick by touching its base and then moving a finger?

1. I usually rely on Apple documentation to help me, that and their source code when available. However one book I can highly recommend is Matt Neuburg's ["Programming in iOS 10".](https://github.com/mattneub/Programming-iOS-Book-Examples) (it is now up to iOS12). He does a great job diving into the various areas of iOS and showing how to accomplish specific tasks. He also provides plenty of cautions about problems you might encounter.

**Comment by jungwook8580** [comment]
1.
Glad that it moves independently haha... thanks...
2. 
Sorry that i exaplained to you exactly...
I know we can fix joystick setting boolean property in JoyStickView.movable as false.
What i want to do is this. 
I want to move joysticks not dragging handle.
I want to press the background in the view So that it can move joysticks not dragging the handle and base. Well maybe i should make another function to move those joysticks...

3.  Thanks for your recommendation, well apple documentation is really hard for me to read... but i think i need to read it more... and i will try to read your recommendation!!

I really appreciate it!
