### ISSUE TITLE
How to convert angles to position of 3d model in Arkit,SceneKit?

### ISSUE THREAD

**Issue by Manoojkumar** [bradhowes/Joystick#5]

**Comment by bradhowes** [comment]
Hi Manobub, can you please provide some additional information about what you are trying to do?

In 3D graphics you have various ways of affecting how the view appears, usually by manipulating/transforming how the model data is mapped to the view and positioning the camera. You will have to figure out what controls you want and how they will affect the transforms. For instance, if you want to have a joystick that rotates an object in the view when the joystick moves left or right, then you would need to translate the polar coordinates given by the joystick into XY and use the +/- X value to control the direction and perhaps the speed of the rotation. The easiest way to convert:

```
x = sin(theta * pi / 180.0) * displacement
y = cos(theta * pi / 180.0) * displacement
```

A quick check shows that with a displacement of 1.0:

* theta = 0.0 gives x = 0 and y = 1
* theta = 90.0 gives x = 1 and y = 0
* theta = 180.0 gives x = 0 and y = -1
* theta = 270.0 gives x = -1 and y = 0

Again, you will have to decide on and plan out the mapping between joystick movement and how it affects what appears on the screen.
