### ISSUE TITLE
How to add direction arrow image at edge the joystick circle image and its should rotate arrow image as per joystick direction

### ISSUE THREAD

**Issue by mohamedaslam** [bradhowes/Joystick#8]
How to add direction arrow image at edge of the joystick circle image and its should rotate image as per joystick direction.

When joystick button is at centre, direction arrow image at corner should be transparent ..when its moves or reach to corner or edge of the circle,direction arrow image its should appears from transparent to normal ...same like below image effect..

Can you please give me some idea or suggestion how to achieve this..

![Screen Shot 2020-11-12 at 4 03 35 PM](https://user-images.githubusercontent.com/2534003/98912740-73a01c80-2501-11eb-9890-9fcea077573a.png)

**Comment by bradhowes** [comment]
Hi,

There are a couple of ways to do what you want. The easiest is to just have two images, one with a little indicator and another without. Then use the `monitor` property to rotate the base like so:

```
        guard let pointyBase = UIImage(named: "PointedBase") else { fatalError() }
        guard let defaultBase = UIImage(named: "UnpointedBase") else { fatalError() }
        let monitor: (JoyStickViewPolarReport) -> Void = { value in
            if value.displacement < 0.1 {
                joystick.baseImage = defaultBase
                return
            }
            let rotation = value.angle * CGFloat.pi / 180.0
            joystick.baseImage = pointyBase.rotate(radians: rotation)
        }
```

The above relies on an extension to UIImage (below works but assumes too much for a generic solution):

```
extension UIImage {
    func rotate(radians: CGFloat) -> UIImage? {
        UIGraphicsBeginImageContextWithOptions(self.size, false, self.scale)
        defer { UIGraphicsEndImageContext() }
        let context = UIGraphicsGetCurrentContext()!
        context.translateBy(x: size.width / 2, y: size.height / 2)
        context.rotate(by: CGFloat(radians))
        self.draw(in: CGRect(x: -self.size.width/2, y: -self.size.height/2, width: self.size.width, height: self.size.height))
        return UIGraphicsGetImageFromCurrentImageContext()
    }
}
```

Another approach -- probably better -- could be to have a separate UIView that lies behind the joystick view which is rotated much the same way but with additional flexibility including working with CoreAnimation layers to do gradient fills and blending. You can apply affine transforms to layers without having to render into a new UIImage; the CALayer and CoreAnimation does all of the compositing for you.

I've updated the example app to demonstrate an implementation of the first approach; the second approach is left as an exercise. 😉

**Comment by mohamedaslam** [comment]
Thank you so much.its working perfect...

**Comment by LiuSky** [comment]
@bradhowes  hello，Can you do a Demo of example 2

> Hi,
> 
> There are a couple of ways to do what you want. The easiest is to just have two images, one with a little indicator and another without. Then use the `monitor` property to rotate the base like so:
> 
> ```
>         guard let pointyBase = UIImage(named: "PointedBase") else { fatalError() }
>         guard let defaultBase = UIImage(named: "UnpointedBase") else { fatalError() }
>         let monitor: (JoyStickViewPolarReport) -> Void = { value in
>             if value.displacement < 0.1 {
>                 joystick.baseImage = defaultBase
>                 return
>             }
>             let rotation = value.angle * CGFloat.pi / 180.0
>             joystick.baseImage = pointyBase.rotate(radians: rotation)
>         }
> ```
> 
> The above relies on an extension to UIImage (below works but assumes too much for a generic solution):
> 
> ```
> extension UIImage {
>     func rotate(radians: CGFloat) -> UIImage? {
>         UIGraphicsBeginImageContextWithOptions(self.size, false, self.scale)
>         defer { UIGraphicsEndImageContext() }
>         let context = UIGraphicsGetCurrentContext()!
>         context.translateBy(x: size.width / 2, y: size.height / 2)
>         context.rotate(by: CGFloat(radians))
>         self.draw(in: CGRect(x: -self.size.width/2, y: -self.size.height/2, width: self.size.width, height: self.size.height))
>         return UIGraphicsGetImageFromCurrentImageContext()
>     }
> }
> ```
> 
> Another approach -- probably better -- could be to have a separate UIView that lies behind the joystick view which is rotated much the same way but with additional flexibility including working with CoreAnimation layers to do gradient fills and blending. You can apply affine transforms to layers without having to render into a new UIImage; the CALayer and CoreAnimation does all of the compositing for you.
> 
> I've updated the example app to demonstrate an implementation of the first approach; the second approach is left as an exercise. 😉
