### ISSUE TITLE
How to make handle stay within the circumference of the base

### ISSUE THREAD

**Issue by srinivas56** [bradhowes/Joystick#9]
In the code which constraints has to be changed, so the handle stays within the base and not go out of the base image.

**Comment by bradhowes** [comment]
Hello. For square or rectangular bases, one can just calculate the proper dimensions of a CGRect and place in the `handleConstraint` attribute. If you really want a circular boundary such that the center is within a certain radial distance from the base center, I recommend putting in your own `handleCenterClamper` function perform the radial calculation (no need to do any square roots if you compare against a squared radius). In the code this property is private, but perhaps it would be better to make it public and customizable.

Does this answer your question?

**Comment by srinivas56** [comment]
The base view width and height is 100x100, which part of the code should be changed and what values has to be put

**Comment by bradhowes** [comment]
Actually I see that the `travel` setting may be more useful here. By default it is set to 1.0 which allows the handle to cover the entire bounds of the view -- values less than 1.0 will reduce the amount of displacement available. If you handle is 25x25 and your base is 100x100 and you do not want the handle to extend at all beyond the base, then one would need to set `travel` to be `(50.0 - 12.5) / 50.0 = 1.0 - 0.25 = 0.75`

**Comment by srinivas56** [comment]
And also there is lag in handle going back to the center, can you please tell the necessary changes in the code to increase the speed of the handle.

https://user-images.githubusercontent.com/74173137/106709250-3a67dc00-661a-11eb-8cbc-ad8017b6c22f.MOV

**Comment by bradhowes** [comment]
I am not quite clear on what lag you are referring to. Regardless, there is nothing being done to keep the handle from returning to the home position once the touch tracking is done. This can easily be seen in the code by looking at what happens within `touchesEnd` method: it just invokes `homePosition` and this simply sets the center of the handle to be the center of the base.

**Comment by bradhowes** [comment]
Hey @srinivas56, I think I found the issue that you alluded to above. I have posted a fix in 3.1.0 which removes the delay moving to the home position.

**Comment by bradhowes** [comment]
Closing for now.
